# Generated by Django 3.0.6 on 2020-05-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='serving',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('b', 'Breakfast'), ('m', 'Main Course'), ('c', 'Cold Beverage'), ('h', 'Hot Beverage'), ('d', 'Dessert')], default='m', max_length=1),
        ),
    ]
