# Generated by Django 3.0.6 on 2020-06-09 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0005_auto_20200605_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturant.FoodItem', unique=True),
        ),
    ]
