# Generated by Django 3.0.6 on 2020-06-09 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resturant', '0008_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='FoodItem',
            new_name='food_id',
        ),
    ]
